
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Ideal extends javax.swing.JFrame {

    /**
     * Creates new form Ideal
     */
    public Ideal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        Hitung = new javax.swing.JButton();
        CobaLagi = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hasil1 = new javax.swing.JTextField();
        hasil2 = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(136, 13, 109, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(31, 39, 35, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(31, 68, 37, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(31, 97, 80, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(31, 123, 85, 16);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(136, 36, 143, 22);

        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });
        getContentPane().add(Tinggi);
        Tinggi.setBounds(136, 65, 65, 22);

        Berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeratActionPerformed(evt);
            }
        });
        getContentPane().add(Berat);
        Berat.setBounds(136, 94, 65, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("cm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(206, 68, 18, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(206, 94, 15, 16);

        rdb1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rdb1.setText("Perempuan");
        getContentPane().add(rdb1);
        rdb1.setBounds(134, 119, 101, 25);

        rdb2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rdb2.setText("Laki - laki");
        rdb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb2);
        rdb2.setBounds(235, 119, 89, 25);

        Hitung.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(31, 147, 75, 25);

        CobaLagi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CobaLagi.setText("Coba Lagi");
        CobaLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobaLagiActionPerformed(evt);
            }
        });
        getContentPane().add(CobaLagi);
        CobaLagi.setBounds(134, 147, 95, 25);

        Keluar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Keluar.setText("Keluar");
        getContentPane().add(Keluar);
        Keluar.setBounds(259, 147, 73, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(53, 188, 197, 16);

        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        getContentPane().add(bb);
        bb.setBounds(255, 185, 57, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(317, 188, 15, 16);

        jLabel10.setBackground(new java.awt.Color(0, 0, 153));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 210, 166, 20);

        hasil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasil1ActionPerformed(evt);
            }
        });
        getContentPane().add(hasil1);
        hasil1.setBounds(50, 230, 300, 30);

        hasil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasil2ActionPerformed(evt);
            }
        });
        getContentPane().add(hasil2);
        hasil2.setBounds(20, 270, 350, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiActionPerformed

    private void BeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeratActionPerformed

    private void rdb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb2ActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
    try{
    String nama = Nama.getText();
    double hasil = 0;
    double tinggi = Double.valueOf(Tinggi.getText());
    double berat = Double.valueOf(Berat.getText());
    String message;
    
    if(rdb1.isSelected()){
      hasil = (tinggi - 100)  *1;
      bb.setText(hasil+"kg");
    }else if(rdb2.isSelected()){
        hasil  = (tinggi-104)*1;
        bb.setText(hasil+"kg");
    }
    String temp =   Double.toString(hasil);
   
    if(hasil<berat){
       
     
        hasil1.setText("Maaf "+Nama.getText()+", Sepertinya anda Overweight:(");
        hasil2.setText("banyaklah berolahragadan hindari makanan berkolesterol");
    }else if(hasil>berat){
        
        hasil1.setText("Maaf "+Nama.getText()+", Sepertinya anda Underweight:(");
        hasil2.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
    }else{
        
        hasil1.setText("Hallo "+Nama.getText()+",Berat badan anda sudah ideal:)");
        hasil2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat:)");
    }
    
    } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kotak Input Belum Terisi Semua" , "Message",
                    JOptionPane.WARNING_MESSAGE);
            }
    
    }//GEN-LAST:event_HitungActionPerformed

    private void hasil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasil1ActionPerformed

    private void hasil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasil2ActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbActionPerformed

    private void CobaLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobaLagiActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_CobaLagiActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ideal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JButton CobaLagi;
    private javax.swing.JButton Hitung;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JTextField bb;
    private javax.swing.JTextField hasil1;
    private javax.swing.JTextField hasil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
