/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form latihan
     */
    public latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        kelas = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Sofia = new javax.swing.JTextField();
        sepuluh = new javax.swing.JTextField();
        Malang = new javax.swing.JTextField();
        nama1 = new javax.swing.JLabel();
        kelas1 = new javax.swing.JLabel();
        alamat1 = new javax.swing.JLabel();
        Sofia1 = new javax.swing.JTextField();
        sepuluh1 = new javax.swing.JTextField();
        Malang1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nama.setText("Nama");
        getContentPane().add(nama);
        nama.setBounds(30, 40, 41, 16);

        kelas.setText("Kelas");
        getContentPane().add(kelas);
        kelas.setBounds(30, 70, 50, 16);

        alamat.setText("Alamat");
        getContentPane().add(alamat);
        alamat.setBounds(30, 100, 50, 20);

        jLabel5.setText("Formulir");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 10, 60, 16);
        getContentPane().add(Sofia);
        Sofia.setBounds(90, 40, 200, 22);
        getContentPane().add(sepuluh);
        sepuluh.setBounds(90, 70, 200, 22);

        Malang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalangActionPerformed(evt);
            }
        });
        getContentPane().add(Malang);
        Malang.setBounds(90, 100, 200, 22);

        nama1.setText("Nama");
        getContentPane().add(nama1);
        nama1.setBounds(30, 180, 33, 16);

        kelas1.setText("Kelas");
        getContentPane().add(kelas1);
        kelas1.setBounds(30, 210, 50, 16);

        alamat1.setText("Alamat");
        getContentPane().add(alamat1);
        alamat1.setBounds(30, 240, 50, 16);
        getContentPane().add(Sofia1);
        Sofia1.setBounds(90, 180, 200, 22);

        sepuluh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepuluh1ActionPerformed(evt);
            }
        });
        getContentPane().add(sepuluh1);
        sepuluh1.setBounds(90, 210, 200, 22);

        Malang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Malang1ActionPerformed(evt);
            }
        });
        getContentPane().add(Malang1);
        Malang1.setBounds(90, 240, 200, 22);

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 140, 79, 25);

        setBounds(0, 0, 418, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void MalangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MalangActionPerformed

    private void sepuluh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepuluh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sepuluh1ActionPerformed

    private void Malang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Malang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Malang1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nama = Sofia.getText();
    Sofia1.setText(nama);
    String kelas = sepuluh.getText();
    sepuluh1.setText(kelas);
    String alamat = Malang.getText();
    Malang1.setText(alamat);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
private void OKEActionPerformed(java.awt.event.ActionEvent evt){
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Malang;
    private javax.swing.JTextField Malang1;
    private javax.swing.JTextField Sofia;
    private javax.swing.JTextField Sofia1;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel alamat1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel kelas;
    private javax.swing.JLabel kelas1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JTextField sepuluh;
    private javax.swing.JTextField sepuluh1;
    // End of variables declaration//GEN-END:variables
}
